"""
Turns whatever file a user uploads (PDF, DOCX, or TXT) into a list of
LangChain Document objects with some basic metadata attached (source
filename, file type, page number). This runs before anything gets masked
or chunked -- it's purely about getting clean text + metadata out of the
raw file.
"""

from pathlib import Path
from typing import BinaryIO

import pymupdf as fitz
from docx import Document
from docx.oxml.ns import qn
from langchain_core.documents import Document as LangChainDocument


SUPPORTED_EXTENSIONS = {".pdf", ".docx", ".txt"}


# Pulls the file extension out of a filename and lowercases it, so ".PDF" and ".pdf" are treated the same way.
def _get_extension(filename: str) -> str:
    return Path(filename).suffix.lower()


# Checks the uploaded filename's extension against the allowed set (pdf, docx, txt) and raises an error if it isn't one of those.
def validate_file(filename: str) -> None:
    extension = _get_extension(filename)

    if extension not in SUPPORTED_EXTENSIONS:
        raise ValueError(
            "Only PDF, DOCX, and TXT files are supported."
        )


# Reads a PDF page by page using pymupdf and creates one Document per page, so an exact page number can be cited later.
# Blank pages are skipped since there is no text to store for them.
def process_pdf(file: BinaryIO, filename: str) -> list[LangChainDocument]:
    documents = []

    file.seek(0)
    pdf_bytes = file.read()

    with fitz.open(stream=pdf_bytes, filetype="pdf") as pdf:
        for page_index, page in enumerate(pdf): # type: ignore
            text = page.get_text("text").strip()

            if not text:
                continue

            documents.append(
                LangChainDocument(
                    page_content=text,
                    metadata={
                        "source": filename,
                        "file_type": "pdf",
                        "page": page_index + 1,
                    },
                )
            )

    return documents


# True Word page breaks (where the text actually wraps to a new printed page) depend on
# font/margins/renderer and aren't stored in the file at all -- but an EXPLICIT page break
# (Ctrl+Enter in Word, or document.add_page_break() when a docx is generated by a script)
# is stored as a <w:br w:type="page"/> run inside a paragraph, and that we can detect.
def _paragraph_has_page_break(paragraph) -> bool:
    for run in paragraph.runs:
        for br in run._element.findall(qn("w:br")):
            if br.get(qn("w:type")) == "page":
                return True
    return False


# Reads a DOCX file and splits it into one Document per explicit page break, so a document
# built with real page breaks (most generated reports/policies are) gets real page numbers
# instead of everything being lumped under page 1. A docx with no page breaks at all just
# comes back as a single page-1 Document, since there's genuinely nothing to split on.
def process_docx(file: BinaryIO, filename: str) -> list[LangChainDocument]:
    file.seek(0)
    document = Document(file)

    documents = []
    current_page_paragraphs = []
    current_page = 1

    def _flush():
        if current_page_paragraphs:
            documents.append(
                LangChainDocument(
                    page_content="\n".join(current_page_paragraphs),
                    metadata={
                        "source": filename,
                        "file_type": "docx",
                        "page": current_page,
                    },
                )
            )

    for paragraph in document.paragraphs:
        text = paragraph.text.strip()
        if text:
            current_page_paragraphs.append(text)

        if _paragraph_has_page_break(paragraph):
            _flush()
            current_page_paragraphs = []
            current_page += 1

    _flush()

    return documents


# Reads a plain text file and decodes it as UTF-8, falling back to replacing any bad characters if decoding fails.
# Wraps the whole file's text into a single Document with page set to 1.
def process_txt(file: BinaryIO, filename: str) -> list[LangChainDocument]:
    file.seek(0)
    raw_data = file.read()

    if isinstance(raw_data, bytes):
        try:
            text = raw_data.decode("utf-8")
        except UnicodeDecodeError:
            text = raw_data.decode("utf-8", errors="replace")
    else:
        text = raw_data

    text = text.strip()

    if not text:
        return []

    return [
        LangChainDocument(
            page_content=text,
            metadata={
                "source": filename,
                "file_type": "txt",
                "page": 1,
            },
        )
    ]


# Validates the file type, then routes it to the right extractor (PDF, DOCX or TXT) based on its extension.
# Raises an error if no readable text came out, since that usually means the file is empty or scanned as images.
def process_document(
    file: BinaryIO,
    filename: str,
) -> list[LangChainDocument]:
    validate_file(filename)

    extension = _get_extension(filename)

    if extension == ".pdf":
        documents = process_pdf(file, filename)

    elif extension == ".docx":
        documents = process_docx(file, filename)

    else:
        documents = process_txt(file, filename)

    if not documents:
        raise ValueError(
            f"No readable text was found in '{filename}'. "
            "The document may be empty or image-based."
        )

    return documents